### ISSUE TITLE
Missing ReadMe.txt

### ISSUE THREAD

**Issue by lheckemann** [le717/Racers-2-Alternate-Installer#1]
This installer doesn't fully work on European copies of the game, which do not contain ReadMe.txt but instead various localised versions:

```
LeesMij.txt
Leggimi.txt
Liesmich-Datei.txt
Lisezmoi.txt
Archivo Léeme.txt
Readme_da.txt
Readme_uk.txt
Viktigt.txt
```

**Comment by le717** [comment]
I never saw this issue. Thanks for reporting, I'll have to look into it now!
